# Site settings
title: Jordy Zagdanski's Portfolio
email: jayzed@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://jordyzagdanski.com"
twitter_username: jzagdanski
github_username:  jayzed

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _scss
  style: :compressed